spring.profiles.active: dev
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    show_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
  datasource:
    url: jdbc:mysql://localhost:13306?&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
    timeout: 600
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
#  server:
#    address: 0.0.0.0