spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 582147500344-f8m5bkeakmbmi20eeera0cuotu42vrfj.apps.googleusercontent.com
            client-secret: 47eX1z-WhyTpcEeu2CPkkKi3
            scope: profile,email
          naver:
            client-id: cyZFywkDHncC9btZyIMo
            client-secret: 3FzjtHlMkj
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response




